### ISSUE TITLE
Does not seem to work with gettext/gettext v4.8.6

### ISSUE THREAD

**Issue by zimdin12** [roborourke/wp-l10n-gen#5]
Fatal error: Uncaught Error: Object of class Gettext\Utils\ParsedComment could not be converted to string in 
C:\laragon\www\[THEME-DIR]\vendor\gettext\gettext\src\Generators\Po.php:40

Stack trace:
#0 C:\laragon\www\[THEME-DIR]\vendor\gettext\gettext\src\Generators\Generator.php(14): Gettext\Generators\Po::toString(Object(Gettext\Translations), Array)
#1 [internal function]: Gettext\Generators\Generator::toFile(Object(Gettext\Translations), 'languages\\balti...', Array)
#2 C:\laragon\www\[THEME-DIR]\vendor\gettext\gettext\src\Translations.php(191): call_user_func_array('Gettext\\Generat...', Array)
#3 C:\laragon\www\[THEME-DIR]\vendor\roborourke\wp-l10n-gen\inc\class-command.php(351): Gettext\Translations->__call('toPoFile', Array)
#4 C:\laragon\www\[THEME-DIR]\vendor\roborourke\wp-l10n-gen\inc\class-command.php(135): WP_L10N_Gen\Command->to(Object(Gettext\Translations), 'pot', 'l in C:\laragon\www\[THEME-DIR]\vendor\gettext\gettext\src\Generators\Po.php on line 40

**Comment by zimdin12** [comment]
Since it works with gettext 4.8.2 then this command would get it to work:
`composer require gettext/gettext:4.8.2`

**Comment by zimdin12** [comment]
Hello. Should I look for another solution ?
